-- author-name unification (variants merged, Surname,name format flipped)
UPDATE book SET author='A.C. Bhaktivedanta Swami Prabhupada', search_text='shrimad bhagavad gita yatharoop srimad bhagavad git yatharup a.c. bhaktivedanta swami prabhupada a c bhaktivedant svami prabhupad', updated_at=CURRENT_TIMESTAMP WHERE id=5;
UPDATE book SET author='Sivananda Math', search_text='bhent: swami shivanand saraswati evam swami satyanand saraswati bhent svami sivanand sarasvati evam svami satyanand sarasvati sivananda math sivanand math', updated_at=CURRENT_TIMESTAMP WHERE id=28;
UPDATE book SET author='Swami Akhandananda Saraswati', search_text='unki kripa unki krip swami akhandananda saraswati svami akhandanand sarasvati', updated_at=CURRENT_TIMESTAMP WHERE id=33;
UPDATE book SET author='Shushma Agarwal', search_text='naya rasta naya rast shushma agarwal susm agarval', updated_at=CURRENT_TIMESTAMP WHERE id=50;
UPDATE book SET author='K.A. Jamuna', search_text='chitra priya chitr priya k.a. jamuna k a jamun', updated_at=CURRENT_TIMESTAMP WHERE id=52;
UPDATE book SET author='Somnath Shukla', search_text='gali aabad hai gali abad hai somnath shukla somnath sukl', updated_at=CURRENT_TIMESTAMP WHERE id=58;
UPDATE book SET author='Ashok Kumar Pandey', search_text='anumurtiyo ka dharatal anumurtiyo k dharatal ashok kumar pandey asok kumar pandey', updated_at=CURRENT_TIMESTAMP WHERE id=85;
UPDATE book SET author='P. Jairaman', search_text='ek chhand chaar hastakchar ek chhand char hastakchar p. jairaman p jairaman', updated_at=CURRENT_TIMESTAMP WHERE id=87;
UPDATE book SET author='Maithili Sharan Gupt', search_text='saket saket maithili sharan gupt maithili saran gupt', updated_at=CURRENT_TIMESTAMP WHERE id=90;
UPDATE book SET author='Ramswaroop Khare', search_text='shatmanyu satmanyu ramswaroop khare ramsvarup khare', updated_at=CURRENT_TIMESTAMP WHERE id=91;
UPDATE book SET author='Nandal Hitaishi', search_text='do pidhiyoon ka abhiyaan do pidhiyun k abhiyan nandal hitaishi nandal hitaisi', updated_at=CURRENT_TIMESTAMP WHERE id=95;
UPDATE book SET author='Vanmali Bharadwaj', search_text='milind mitram milind mitram vanmali bharadwaj vanmali bharadvaj', updated_at=CURRENT_TIMESTAMP WHERE id=119;
UPDATE book SET author='Bhikshu Dharmrakshit', search_text='kalam gantantra ka keshputra kalam gantantr k kesputr bhikshu dharmrakshit bhiksu dharmraksit', updated_at=CURRENT_TIMESTAMP WHERE id=120;
UPDATE book SET author='Bhagwati Charan Verma', search_text='meri priya kahaniyan meri priya kahaniyan bhagwati charan verma bhagvati charan verm', updated_at=CURRENT_TIMESTAMP WHERE id=123;
UPDATE book SET author='Shyam Narayan Pandey', search_text='haldighati haldighati shyam narayan pandey syam narayan pandey', updated_at=CURRENT_TIMESTAMP WHERE id=124;
UPDATE book SET author='Swami Akhandananda Saraswati', search_text='sati draupadi sati draupadi swami akhandananda saraswati svami akhandanand sarasvati', updated_at=CURRENT_TIMESTAMP WHERE id=125;
UPDATE book SET author='Shriprakash Mani Tripathi', search_text='samkaleen rajnitik chintan samkalin rajnitik chintan shriprakash mani tripathi sriprakas mani tripathi', updated_at=CURRENT_TIMESTAMP WHERE id=127;
UPDATE book SET author='John Lourie', search_text='don''t let go don t let go john lourie john lourie', updated_at=CURRENT_TIMESTAMP WHERE id=181;
UPDATE book SET author='A.P.J. Abdul Kalam', search_text='advantage india: from challenge to opportunity advantage india from challenge to opportunity a.p.j. abdul kalam a p j abdul kalam', updated_at=CURRENT_TIMESTAMP WHERE id=207;
UPDATE book SET author='P.G. Wodehouse', search_text='jeeves takes charge jives takes charge p.g. wodehouse p g vodehouse', updated_at=CURRENT_TIMESTAMP WHERE id=208;
UPDATE book SET author='R.K. Agarwala', search_text='hindu law hindu lav r.k. agarwala r k agarval', updated_at=CURRENT_TIMESTAMP WHERE id=249;
UPDATE book SET author='G. Ram Reddy (Ed.)', search_text='developing society & police developing society police g. ram reddy (ed.) g ram reddy ed', updated_at=CURRENT_TIMESTAMP WHERE id=254;
UPDATE book SET author='J.K. Rowling', search_text='harry potter and the half-blood prince harry potter and the half blud prince j.k. rowling j k rovling', updated_at=CURRENT_TIMESTAMP WHERE id=258;
UPDATE book SET author='Ruskin Bond (Ed.)', search_text='the rupa book of nightmare tales the rup buk of nightmare tales ruskin bond (ed.) ruskin bond ed', updated_at=CURRENT_TIMESTAMP WHERE id=308;
UPDATE book SET author='Vaijnath Pandey', search_text='charan paduka charan paduk vaijnath pandey vaijnath pandey', updated_at=CURRENT_TIMESTAMP WHERE id=447;
UPDATE book SET author='Maithili Sharan Gupt', search_text='yashodhara yasodhar maithili sharan gupt maithili saran gupt', updated_at=CURRENT_TIMESTAMP WHERE id=474;
UPDATE book SET author='Trilokinath Brijlal (Ed.)', search_text='dwama nibandh sangrah dvam nibandh sangrah trilokinath brijlal (ed.) trilokinath brijlal ed', updated_at=CURRENT_TIMESTAMP WHERE id=475;
UPDATE book SET author='Rajesh Dixit', search_text='geet godawari git godavari rajesh dixit rajes dixit', updated_at=CURRENT_TIMESTAMP WHERE id=480;
UPDATE book SET author='Suresh Pandey', search_text='band zindagi aur vidhroh band zindagi aur vidhroh suresh pandey sures pandey', updated_at=CURRENT_TIMESTAMP WHERE id=481;
UPDATE book SET author='Nishith Ranjan Tiwari', search_text='jangal ki oor jangal ki ur nishith ranjan tiwari nisith ranjan tivari', updated_at=CURRENT_TIMESTAMP WHERE id=485;
UPDATE book SET author='Vanmali Bharadwaj', search_text='varna rahayam varn rahayam vanmali bharadwaj vanmali bharadvaj', updated_at=CURRENT_TIMESTAMP WHERE id=490;
UPDATE book SET author='Madan Mohan Sarma', search_text='manas moti manas moti madan mohan sarma madan mohan sarm', updated_at=CURRENT_TIMESTAMP WHERE id=587;
UPDATE book SET author='Rajbali Pandey', search_text='hindu sanskar hindu sanskar rajbali pandey rajbali pandey', updated_at=CURRENT_TIMESTAMP WHERE id=589;
UPDATE book SET author='Nishith Ranjan Tiwari', search_text='mrityu ke par mrityu ke par nishith ranjan tiwari nisith ranjan tivari', updated_at=CURRENT_TIMESTAMP WHERE id=591;
UPDATE book SET author='Ashok Pandey', search_text='mahaprasad mahaprasad ashok pandey asok pandey', updated_at=CURRENT_TIMESTAMP WHERE id=598;
UPDATE book SET author='Girish Pandey', search_text='jeevokreshi jivokresi girish pandey giris pandey', updated_at=CURRENT_TIMESTAMP WHERE id=616;
UPDATE book SET author='Gayatri Singh', search_text='jheel mein tairty machliyan jhil mein tairty machliyan gayatri singh gayatri singh', updated_at=CURRENT_TIMESTAMP WHERE id=617;
UPDATE book SET author='Shyam Sunder Goswami', search_text='raag chaaplushi rag chaplusi shyam sunder goswami syam sunder gosvami', updated_at=CURRENT_TIMESTAMP WHERE id=629;
UPDATE book SET author='Rajesh Dixit', search_text='geet kadadmbini git kadadmbini rajesh dixit rajes dixit', updated_at=CURRENT_TIMESTAMP WHERE id=634;
UPDATE book SET author='Roopkumar Mishr', search_text='srajan ke swer srajan ke sver roopkumar mishr rupkumar misr', updated_at=CURRENT_TIMESTAMP WHERE id=635;
UPDATE book SET author='Gyanendra Kumar Singh Chauhan', search_text='roshini ki ankh num hai rosini ki ankh num hai gyanendra kumar singh chauhan gyanendr kumar singh chauhan', updated_at=CURRENT_TIMESTAMP WHERE id=642;
UPDATE book SET author='Rajendra Pratap Singh (Ed.)', search_text='we bhi insan the ve bhi insan the rajendra pratap singh (ed.) rajendr pratap singh ed', updated_at=CURRENT_TIMESTAMP WHERE id=648;
UPDATE book SET author='Girish Pandey', search_text='jevocresi jevocresi girish pandey giris pandey', updated_at=CURRENT_TIMESTAMP WHERE id=649;
UPDATE book SET author='Anant Sharma', search_text='rachna prasoon rachn prasun anant sharma anant sarm', updated_at=CURRENT_TIMESTAMP WHERE id=656;
UPDATE book SET author='Urfi Kalim', search_text='my love my love urfi kalim urfi kalim', updated_at=CURRENT_TIMESTAMP WHERE id=682;
UPDATE book SET author='Marina Andrade', search_text='the magic wheels and other stories the magic vhils and other stories marina andrade marin andrade', updated_at=CURRENT_TIMESTAMP WHERE id=697;
UPDATE book SET author='D.H. Lawrence', search_text='a propos of lady chatterley''s lover a propos of lady chatterley s lover d.h. lawrence d h lavrence', updated_at=CURRENT_TIMESTAMP WHERE id=712;
UPDATE book SET author='J.C. Johari', search_text='comparative politics comparative politics j.c. johari j c johari', updated_at=CURRENT_TIMESTAMP WHERE id=721;
UPDATE book SET author='J.K. Rowling', search_text='harry potter and the order of the phoenix harry potter and the order of the foenix j.k. rowling j k rovling', updated_at=CURRENT_TIMESTAMP WHERE id=736;
UPDATE book SET author='Madhuri Tiwari', search_text='shab-e-furkat sab e furkat madhuri tiwari madhuri tivari', updated_at=CURRENT_TIMESTAMP WHERE id=845;
UPDATE book SET author='Shakuntala Shirodiya', search_text='mere perdeshi mere perdesi shakuntala shirodiya sakuntal sirodiya', updated_at=CURRENT_TIMESTAMP WHERE id=847;
UPDATE book SET author='Harihar Prasad Gupta', search_text='safalta ke liye kya karein? safalt ke liye kya karein harihar prasad gupta harihar prasad gupt', updated_at=CURRENT_TIMESTAMP WHERE id=848;
UPDATE book SET author='J.K. Rowling', search_text='the tale of beedle the bard the tale of bidle the bard j.k. rowling j k rovling', updated_at=CURRENT_TIMESTAMP WHERE id=854;
UPDATE book SET author='R.K. Narayan', search_text='swami and friends svami and friends r.k. narayan r k narayan', updated_at=CURRENT_TIMESTAMP WHERE id=858;
UPDATE book SET author='A.C. Bhaktivedanta Swami Prabhupada', search_text='perfect questions, perfect answers perfect questions perfect ansvers a.c. bhaktivedanta swami prabhupada a c bhaktivedant svami prabhupad', updated_at=CURRENT_TIMESTAMP WHERE id=859;
UPDATE book SET author='A.C. Bhaktivedanta Swami Prabhupada', search_text='the path of perfection the path of perfection a.c. bhaktivedanta swami prabhupada a c bhaktivedant svami prabhupad', updated_at=CURRENT_TIMESTAMP WHERE id=861;
UPDATE book SET author='A.P.J. Abdul Kalam', search_text='turning points: a journey through challenges turning points a journey through challenges a.p.j. abdul kalam a p j abdul kalam', updated_at=CURRENT_TIMESTAMP WHERE id=882;
UPDATE book SET author='Shobha Tripathi', search_text='zewar- kahani sangrah zevar kahani sangrah shobha tripathi sobh tripathi', updated_at=CURRENT_TIMESTAMP WHERE id=902;
UPDATE book SET author='Savitri Devi Verma', search_text='suno kan mein suno kan mein savitri devi verma savitri devi verm', updated_at=CURRENT_TIMESTAMP WHERE id=906;
UPDATE book SET author='J.K. Rowling, John Tiffany & Jack Thorne', search_text='harry potter and the cursed child harry potter and the cursed child j.k. rowling, john tiffany & jack thorne j k rovling john tiffany jack thorne', updated_at=CURRENT_TIMESTAMP WHERE id=916;
UPDATE book SET author='J.K. Rowling', search_text='harry potter and the goblet of fire harry potter and the goblet of fire j.k. rowling j k rovling', updated_at=CURRENT_TIMESTAMP WHERE id=918;
UPDATE book SET author='D.H. Lawrence', search_text='sons and lovers sons and lovers d.h. lawrence d h lavrence', updated_at=CURRENT_TIMESTAMP WHERE id=921;
UPDATE book SET author='Swami Akhandananda Saraswati', search_text='shri bhishma pitamah sri bhism pitamah swami akhandananda saraswati svami akhandanand sarasvati', updated_at=CURRENT_TIMESTAMP WHERE id=942;
UPDATE book SET author='A.C. Bhaktivedanta Swami Prabhupada', search_text='mrityu ki parajay mrityu ki parajay a.c. bhaktivedanta swami prabhupada a c bhaktivedant svami prabhupad', updated_at=CURRENT_TIMESTAMP WHERE id=944;
UPDATE book SET author='Swami Akhandananda Saraswati', search_text='vedant bodh vedant bodh swami akhandananda saraswati svami akhandanand sarasvati', updated_at=CURRENT_TIMESTAMP WHERE id=945;
UPDATE book SET author='Swami Akhandananda Saraswati', search_text='sundar kand sundar kand swami akhandananda saraswati svami akhandanand sarasvati', updated_at=CURRENT_TIMESTAMP WHERE id=952;
UPDATE book SET author='A.C. Bhaktivedanta Swami Prabhupada', search_text='rasraj shri krishna rasraj sri krisn a.c. bhaktivedanta swami prabhupada a c bhaktivedant svami prabhupad', updated_at=CURRENT_TIMESTAMP WHERE id=958;
UPDATE book SET author='Swami Akhandananda Saraswati', search_text='krishna krishna ke ucharan se krishna prapti krisn krisn ke ucharan se krisn prapti swami akhandananda saraswati svami akhandanand sarasvati', updated_at=CURRENT_TIMESTAMP WHERE id=959;
UPDATE book SET author='Usha Priyamvada', search_text='seedhiyan sidhiyan usha priyamvada us priyamvad', updated_at=CURRENT_TIMESTAMP WHERE id=969;
UPDATE book SET author='Trinath Mishra', search_text='kahaniyan kahaniyan trinath mishra trinath misr', updated_at=CURRENT_TIMESTAMP WHERE id=972;
UPDATE book SET author='Sartaj Mathur', search_text='abhishapt abhisapt sartaj mathur sartaj mathur', updated_at=CURRENT_TIMESTAMP WHERE id=975;
UPDATE book SET author='Suresh Kant (Ed.)', search_text='vishwa prasiddh kahaniyan bhag 4 visv prasiddh kahaniyan bhag 4 suresh kant (ed.) sures kant ed', updated_at=CURRENT_TIMESTAMP WHERE id=987;
UPDATE book SET author='Asharam Tripathi', search_text='chaturdarshi chaturdarsi asharam tripathi asaram tripathi', updated_at=CURRENT_TIMESTAMP WHERE id=998;
UPDATE book SET author='John Lourie', search_text='rinning for the life rinning for the life john lourie john lourie', updated_at=CURRENT_TIMESTAMP WHERE id=1066;
UPDATE book SET author='Umesh Singh Chauhan', search_text='ganth mein lo bandh thodi chandni ganth mein lo bandh thodi chandni umesh singh chauhan umes singh chauhan', updated_at=CURRENT_TIMESTAMP WHERE id=1281;
UPDATE book SET author='R.S. Gopal', search_text='ehsaas ehsas r.s. gopal r s gopal', updated_at=CURRENT_TIMESTAMP WHERE id=1282;
UPDATE book SET author='Arvind Raahi', search_text='drishtiaur srihti dristiaur srihti arvind raahi arvind rahi', updated_at=CURRENT_TIMESTAMP WHERE id=1285;
UPDATE book SET author='Khaliqur Rahman', search_text='out if the middle out if the middle khaliqur rahman khaliqur rahman', updated_at=CURRENT_TIMESTAMP WHERE id=1295;
UPDATE book SET author='R.C. Majumdar', search_text='ancient india ancient india r.c. majumdar r c majumdar', updated_at=CURRENT_TIMESTAMP WHERE id=1297;
UPDATE book SET author='N.S. Saksena', search_text='communal riots in india communal riots in india n.s. saksena n s saksen', updated_at=CURRENT_TIMESTAMP WHERE id=1326;
UPDATE book SET author='N.V. Paranjape', search_text='criminology and penology criminology and penology n.v. paranjape n v paranjape', updated_at=CURRENT_TIMESTAMP WHERE id=1333;
UPDATE book SET author='Harimohan Singh Kothiya', search_text='dhara ke bol dhar ke bol harimohan singh kothiya harimohan singh kothiya', updated_at=CURRENT_TIMESTAMP WHERE id=1380;
UPDATE book SET author='Harihar Prasad Gupta', search_text='sudama sudam harihar prasad gupta harihar prasad gupt', updated_at=CURRENT_TIMESTAMP WHERE id=1386;
UPDATE book SET author='Usha Kanak Pathak', search_text='yaagseni yagseni usha kanak pathak us kanak pathak', updated_at=CURRENT_TIMESTAMP WHERE id=1392;
UPDATE book SET author='Ashok Kumar Dubey', search_text='prenna prenn ashok kumar dubey asok kumar dubey', updated_at=CURRENT_TIMESTAMP WHERE id=1393;
UPDATE book SET author='John Lourie', search_text='sneaking in sneaking in john lourie john lourie', updated_at=CURRENT_TIMESTAMP WHERE id=1414;
UPDATE book SET author='Satendra Kumar Raghuvanshi', search_text='kitni door aur chalne per kitni dur aur chalne per satendra kumar raghuvanshi satendr kumar raghuvansi', updated_at=CURRENT_TIMESTAMP WHERE id=1501;
UPDATE book SET author='Virendra Bhatnagar', search_text='television television virendra bhatnagar virendr bhatnagar', updated_at=CURRENT_TIMESTAMP WHERE id=1503;
UPDATE book SET author='Savitri Saxena', search_text='kuch man biti kuch jag biti kuch man biti kuch jag biti savitri saxena savitri saxen', updated_at=CURRENT_TIMESTAMP WHERE id=1532;
UPDATE book SET author='Bhagwan Sharan Bhardwaj', search_text='ramcharitmanas aur adhunik jeevan ki samasyaen ramcharitmanas aur adhunik jivan ki samasyaen bhagwan sharan bhardwaj bhagvan saran bhardvaj', updated_at=CURRENT_TIMESTAMP WHERE id=1546;
UPDATE book SET author='Pramod Kumar Agarwal', search_text='sahib ganj ki bahu sahib ganj ki bahu pramod kumar agarwal pramod kumar agarval', updated_at=CURRENT_TIMESTAMP WHERE id=1549;
UPDATE book SET author='Shakir Ansari', search_text='nawa-e gul nav e gul shakir ansari sakir ansari', updated_at=CURRENT_TIMESTAMP WHERE id=1626;
UPDATE book SET author='Uttam Swami', search_text='dharmacharan:parmanand ka rahasya dharmacharan parmanand k rahasya uttam swami uttam svami', updated_at=CURRENT_TIMESTAMP WHERE id=1681;
UPDATE book SET author='Chanra Bhushan Pandey', search_text='gayatri ka chaitanya satta me leela vilas gayatri k chaitanya satt me lil vilas chanra bhushan pandey chanr bhusan pandey', updated_at=CURRENT_TIMESTAMP WHERE id=1691;
UPDATE book SET author='Kripashanker Shukla (Ed.)', search_text='purvanchal ki maati kavya sanklan purvanchal ki mati kavya sanklan kripashanker shukla (ed.) kripasanker sukl ed', updated_at=CURRENT_TIMESTAMP WHERE id=1698;
UPDATE book SET author='Ranvijay Singh', search_text='sarkar banane ke achook nuskhe sarkar banane ke achuk nuskhe ranvijay singh ranvijay singh', updated_at=CURRENT_TIMESTAMP WHERE id=1700;
UPDATE book SET author='Narendra Mishra', search_text='amerbail balidan ki amerbail balidan ki narendra mishra narendr misr', updated_at=CURRENT_TIMESTAMP WHERE id=1733;
UPDATE book SET author='Shri Ashutosh Bandopadhyay', search_text='geeta satya probodhni dwitiya khand i git satya probodhni dvitiya khand i shri ashutosh bandopadhyay sri asutos bandopadhyay', updated_at=CURRENT_TIMESTAMP WHERE id=1765;
