#!/usr/bin/env python3
"""Merge the catalog-cleanup agents' output into UPDATE statements.

Reads the original export + out/*.json chunks from the scratchpad, applies
high/medium-confidence corrections (low-confidence rows keep original fields
and get no summary), recomputes search_text, and writes:
  revamp/app/seed/enrichment.sql   -- UPDATEs to run against D1
  revamp/data/enrichment_review.csv -- every change, for human review
"""
import csv
import json
import re
import sys
from pathlib import Path

SCRATCH = Path("/private/tmp/claude-501/-Users-anshuman-code-LibrarySuryaFoundation"
               "/8965b9a9-9034-46e6-8a94-00c6a5d151de/scratchpad")
ROOT = Path(__file__).resolve().parent.parent
SQL_OUT = ROOT / "app" / "seed" / "enrichment.sql"
CSV_OUT = ROOT / "data" / "enrichment_review.csv"

FIELDS = ["title", "author", "publisher", "pub_year", "language"]


def fold(s):  # same folding as tools/migrate.py, for search_text
    if not s:
        return ""
    s = s.lower()
    s = re.sub(r"[^a-z0-9\s]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    words = []
    for w in s.split(" "):
        w = re.sub(r"aa+", "a", w)
        w = re.sub(r"ee+", "i", w)
        w = re.sub(r"ii+", "i", w)
        w = re.sub(r"oo+", "u", w)
        w = re.sub(r"uu+", "u", w)
        w = w.replace("w", "v").replace("chch", "ch")
        w = w.replace("sh", "s").replace("ph", "f")
        w = re.sub(r"([bcdfghjklmnpqrstvz])a$", r"\1", w)
        words.append(w)
    return " ".join(words)


def sql_str(v):
    if v is None or v == "":
        return "NULL"
    if isinstance(v, int):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    original = {b["id"]: b for b in
                json.load((SCRATCH / "books_export.json").open())[0]["results"]}
    results = {}
    for f in sorted((SCRATCH / "out").glob("out_*.json")):
        for r in json.load(f.open()):
            results[r["id"]] = r
    missing = set(original) - set(results)
    extra = set(results) - set(original)
    print(f"original={len(original)} results={len(results)} "
          f"missing={len(missing)} extra={len(extra)}")
    if extra:
        sys.exit(f"ABORT: agents invented ids: {sorted(extra)[:10]}")
    if missing:
        print(f"WARNING: {len(missing)} books got no result; leaving untouched")

    stats = {"high": 0, "medium": 0, "low": 0, "field_changes": 0,
             "summaries": 0, "unchanged": 0}
    updates, review = [], []
    for bid, orig in sorted(original.items()):
        r = results.get(bid)
        if not r:
            continue
        conf = r.get("confidence", "low")
        stats[conf] = stats.get(conf, 0) + 1
        new = dict(orig)
        changed_fields = []
        if conf in ("high", "medium"):
            for f in FIELDS:
                v = r.get(f)
                if f == "pub_year" and v is not None:
                    try:
                        v = int(v)
                    except (TypeError, ValueError):
                        v = orig["pub_year"]
                if v and v != orig[f]:
                    new[f] = v
                    changed_fields.append(f)
            summary = (r.get("summary") or "").strip() or None
            if summary:
                new["summary"] = summary
                stats["summaries"] += 1
        else:
            summary = None
        if not changed_fields and not summary:
            stats["unchanged"] += 1
            continue
        stats["field_changes"] += len(changed_fields)
        search = " ".join(x for x in [
            (new["title"] or "").lower(), fold(new["title"]),
            (new["author"] or "").lower(), fold(new["author"])] if x)
        updates.append(
            "UPDATE book SET "
            f"title={sql_str(new['title'])}, author={sql_str(new['author'])}, "
            f"publisher={sql_str(new['publisher'])}, "
            f"pub_year={sql_str(new['pub_year'])}, "
            f"language={sql_str(new['language'])}, "
            f"summary={sql_str(new.get('summary'))}, "
            f"search_text={sql_str(search)}, "
            f"updated_at=CURRENT_TIMESTAMP WHERE id={bid};")
        for f in changed_fields:
            review.append({"id": bid, "field": f,
                           "old": orig[f], "new": new[f], "confidence": conf})

    SQL_OUT.write_text("-- generated by tools/apply_enrichment.py\n"
                       + "\n".join(updates) + "\n")
    with CSV_OUT.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, ["id", "field", "old", "new", "confidence"])
        w.writeheader()
        w.writerows(review)
    print(f"wrote {SQL_OUT} ({len(updates)} UPDATEs)")
    print(f"wrote {CSV_OUT} ({len(review)} field changes)")
    print("stats:", stats)


if __name__ == "__main__":
    main()
